#DataSoure Config
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/house?useSSL=false&useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 153277
  mail:
    # qq
    host: smtp.qq.com
    port:
    username: 1532771197@qq.com
    password: czmpzlyhnmcoheba
    protocol: smtp
    default-encoding: UTF-8
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
      mail.smtp.starttls.required: true
      mail.smtp.socketFactory.port: 465
      mail.smtp.socketFactory.class: javax.net.ssl.SSLSocketFactory

mybatis-plus:
  mapper-locations: classpath*:/mapper/**Mapper.xml
  global-config:
    db-config:
      #      logic-delete-field: deleted  # 全局逻辑删除的实体字段名
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)

server:
  port: 8882
shiro-redis:
  enabled: true
  redis-manager: 127.0.0.1:6379

lbb:
  jwt:
    #加密密钥(自己定义，一点要长)
    secret: f4e2e52034348f86b67cde581c0f9eb5
    #token 有效时长7天，单位秒
    expire: 6048000
    header: Authorization

logging:
  level:
    com.lbb.vuehousespringboot.mapper: debug

